### ISSUE TITLE
TLS negotiation fails 

### ISSUE THREAD

**Issue by jonyt** [aws/aws-iot-device-sdk-java-v2#116] opened 2020-12-02 19:50 UTC
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-java-v2/issues) and didn't find any solution

**Known Issue**
- [x ] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Describe the bug**
I'm trying to connect to the IoT data endpoint using Websockets and a proxy and failing with `java.util.concurrent.ExecutionException: software.amazon.awssdk.crt.mqtt.MqttException: TLS (SSL) negotiation failed`. I enabled the Apache HTTP wire logs as well as the netty logs and also captured the traffic using tcpdump. I can see the SDK trying to retrieve temporary credentials from the IoT credential endpoint, and apparently succeeding. Subsequently the SDK tries to connect to the data endpoint, succeeds and then gets disconnected. The above exception is thrown. 

**SDK version number**
1.2.5

**Platform/OS/Hardware/Device**
Amazon Linux, java SE 1.8.0_92

**To Reproduce (observed behavior)**

```
MqttClientConnectionEvents callbacks = new MqttClientConnectionEvents() {
	@Override
	public void onConnectionInterrupted(int errorCode) {
		if (errorCode != 0) {
			logger.warn("Connection interrupted: " + errorCode + ": " + CRT.awsErrorString(errorCode) + ", messagingClientId = " + messagingClientId);
		}
	}

	@Override
	public void onConnectionResumed(boolean sessionPresent) {
		logger.warn("Connection resumed: " + (sessionPresent ? "existing session" : "clean session") + ", messagingClientId = " + messagingClientId);
	}
};
logger.debug("Initiating connection to AWS IoT. Messaging client ID: {}, endpoint: {}, certificate length: {}, key length: {}, CA length: {}", messagingClientId, iotEndpoint, certificate.length(), privateKey.length(), certificateAuthority.length());
eventLoopGroup = new EventLoopGroup(1);
resolver = new HostResolver(eventLoopGroup);
clientBootstrap = new ClientBootstrap(eventLoopGroup, resolver);
builder = AwsIotMqttConnectionBuilder.newMtlsBuilder(certificate, privateKey);

builder.withCertificateAuthority(certificateAuthority)
		.withBootstrap(clientBootstrap)
		.withCleanSession(false)
		.withEndpoint(iotEndpoint)
		.withConnectionEventCallbacks(callbacks)
		.withClientId(messagingClientId);

if (proxyHost != null) {
	logger.info("Using proxy {}:{}, IoT credential endpoint: {}, role alias {}", proxyHost, proxyPort, iotCredentialEndpoint, roleAlias);
	HttpProxyOptions proxyOptions = new HttpProxyOptions();
	proxyOptions.setHost(proxyHost);
	proxyOptions.setPort(proxyPort);
	builder.withWebsockets(true).withWebsocketSigningRegion(iotCredentialRegion.id()).withWebsocketProxyOptions(proxyOptions);
	try (TlsContextOptions x509TlsOptions = TlsContextOptions.createWithMtls(certificate, privateKey)) {
		x509TlsOptions.withCertificateAuthority(certificateAuthority);

		try (ClientTlsContext x509TlsContext = new ClientTlsContext(x509TlsOptions)) {
			X509CredentialsProvider.X509CredentialsProviderBuilder x509builder = new X509CredentialsProvider.X509CredentialsProviderBuilder()
					.withClientBootstrap(clientBootstrap)
					.withTlsContext(x509TlsContext)
					.withEndpoint(iotCredentialEndpoint)
					.withRoleAlias(roleAlias)
					.withThingName(messagingClientId)
					.withProxyOptions(proxyOptions);
			try (X509CredentialsProvider provider = x509builder.build()) {
				builder.withWebsocketCredentialsProvider(provider);
				logger.debug("All proxy options set");
			}
		}
	}
}

connection = builder.build();
try {
	boolean isResumed = connection.connect().get(30, TimeUnit.SECONDS);
	this.logger.info("Connected to AWS IoT. {}", isResumed ? "Resuming session" : "New session");
} catch (InterruptedException | ExecutionException | TimeoutException e) {
	throw new IllegalStateException("Unable to connect to AWS IoT", e);
} 
```

**Expected behavior**
Connection should be established with no error.

**Logs/output**

```
[INFO ] [2020-12-02T13:59:07Z] [00007fcc30abc700] [http-connection] - (0x7fcc2802b5c0) Proxy connection made successful CONNECT request to "xxxxxxx-ats.iot.us-west-2.amazonaws.com" via proxy
[INFO ] [2020-12-02T13:59:07Z] [00007fcc30abc700] [http-connection] - (0x7fcc2802b5c0) Beginning TLS negotiation
[WARN ] [2020-12-02T13:59:07Z] [00007fcc30abc700] [tls-handler] - id=0x7fcc28021600: negotiation failed with error Bad message encountered (Error encountered in /codebuild/output/src990005344/src/aws-crt-java/aws-common-runtime/s2n/tls/s2n_handshake_io.c line 1001)
[ERROR] [2020-12-02T13:59:07Z] [00007fcc30abc700] [http-connection] - (0x7fcc2802b5c0) Proxy connection failed origin server TLS negotiation with error 1029(TLS (SSL) negotiation failed)
[INFO ] [2020-12-02T13:59:07Z] [00007fcc30abc700] [http-connection] - 0x7fcc2802b5c0: Client shutdown completed with error 0 (AWS_ERROR_SUCCESS).
[ERROR] [2020-12-02T13:59:07Z] [00007fcc30abc700] [http-connection] - (0x7fcc2802b5c0) Error 1029 while connecting to "xxxxxx-ats.iot.us-west-2.amazonaws.com" via proxy.
[ERROR] [2020-12-02T13:59:07Z] [00007fcc30abc700] [websocket-setup] - id=0x7fcc28033880: Websocket setup failed to establish HTTP connection, error 1029 (AWS_IO_TLS_ERROR_NEGOTIATION_FAILURE).
```

**Additional context**
I know the server I'm running this on together with the role alias/policy/certificate/proxy combination is ok since running theBasicPubSub sample on this server with the same role alias/policy/certificate/proxy combination  works fine. I also know the code itself is ok since it works on a different server.

**Comment by bretambrose** [comment] 2020-12-02 22:03
It looks like you're applying the certificate and key to the top level connection's tls context (via the builder) rather than to just the X509 configuration.  You'll want to change the builder to be constructed via a WebsocketConfig object.  The basic pub sub sample shows an example if you follow the web socket/x509 logic flow.

**Comment by jonyt** [comment] 2020-12-03 08:28
Thanks for getting back to me.

I don't understand. The code I have is copied from the BasicPubSub example. I also can't find a WebsocketConfig class in this SDK or the AWS SDK. Is there an example you can give me of how to do this correctly? What part of my code is wrong?

(And a side note: this code works well on other servers)

**Comment by bretambrose** [comment] 2020-12-03 16:31
Oops, I was thinking this was a v2 CPP sdk issue.

Looking again, my guess is that you're passing in values to "certificate" and "privateKey"  The way the sample is written, websockets won't work if you set the top tls context with anything other than null, null.  We should update the sample to make this clearer and make it impossible to accidentally configure conflicting options like that.

**Comment by jmklix** [comment] 2020-12-16 00:07
@jonyt are you still having problems with the TLS negotiations? 

Based on the feature request you made it appears you figured out the cause of your errors, but I wanted to make sure you got it working before closing this issue.

**Comment by jonyt** [comment] 2020-12-16 08:59
Yes, please close it.

**Closed** 2020-12-16 16:18 UTC
Labels: guidance
